# Generated by Django 6.0.3 on 2026-03-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=25)),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_contanct', models.IntegerField(max_length=15)),
            ],
        ),
    ]
